version: '3.8'

services:
  movie-list-api:
    build: .
    container_name: movie-list-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
